spring:
    servlet:
          multipart:
              max-file-size: -1
              max-request-size: -1
    cloud:
      config:
        enabled: true
    
    datasource:
          url: jdbc:h2:tcp://localhost/~/moviesquare/japan/db        
          username: sa
          password: 
          driver-class-name: org.h2.Driver
    jpa: 
        generate-ddl: true
        hibernate:
          ddl-auto : update
    eureka:
        instance:
        preferIpAddress: true
        client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
  
    logging.level: 
        com.japan.movie: debug
  
server:
  port: 8081
  
spring:
  output:
    ansi:
      enabled: always # make color
  application:
    name: japan
  profiles:
    active: default