spring:  
    application.name: moviesquareservice
    servlet.multipart:
        max-file-size: -1
        max-request-size: -1
    thymeleaf.cache: false
    profiles.active: default
    cloud.config.enabled: true
   
            
feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000
spring.profiles.include : oauth2
server.servlet.session.tracking-modes : cookie   

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    