spring:
    cloud.config.enabled: true
    application.name : memberservice
    
    datasource:
          url: jdbc:h2:tcp://localhost/~/moviesquare/member/db        
          username: sa
          password: 
          driver-class-name: org.h2.Driver
    jpa: 
        generate-ddl: true
        hibernate.ddl-auto : update
    



eureka:
    instance.preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl.defaultZone: http://localhost:8761/eureka/
  

  
