server.port : 8119

spring:
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
    output.ansi.enabled: always
    application.name : korea
    profiles.active : default
    datasource:
      url: jdbc:h2:tcp://localhost/~/moviesquare/korea/db        
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    jpa: 
      generate-ddl: true
      hibernate.ddl-auto: update
    servlet.multipart.max-request-size: -1
    thymeleaf.cache: false
    cloud:
        config.enbled: true





eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/